### PR TITLE
Bump all major versions capped by `^` constraints

### LINKED ISSUE #29: Upgrade to `myst-parser` v4
Hey @ashwinvis, any plan for a `1.4.0` release to bump the dependency from `myst-parser = "^2.0.0"` to `myst-parser = "^3.0.0"`? 🤗

### PR DESCRIPTION
**Pull request by kdeldycke**
Attempt to close #29 and see how the test suite is reacting.

I went full stream ahead and upgraded all the major revisions that were capping by a `^` specifiers.

### CODE REVIEW

**Comment by kdeldycke** [comment]
[`sphinxcontrib-bibtex`](https://github.com/mcmtroffaes/sphinxcontrib-bibtex) is broken on Python 3.12, so we are waiting for a new release upstream. See: https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/345

**Comment by ashwinvis** [comment]
Thanks for going through all those checks. Usually PyPI would not accept git or even arbitary URL in mandatory dependencies. However it is OK to add this version under test-group and lock it.

**Comment by ashwinvis** [comment]
After reading the linked issue, it seems to me issue is fixed upstream in`pybtex`.

https://bitbucket.org/pybtex-devs/pybtex/commits/7066984c8776e3115ae8c78c22c695a184233ef5

Perhaps we can pin that instead in the test-group and remove the unnecessary setuptool dependency. What do you think?

**Comment by kdeldycke** [comment]
> Thanks for going through all those checks. Usually PyPI would not accept git or even arbitary URL in mandatory dependencies. However it is OK to add this version under test-group and lock it.

Yeah, I just relied on upstream versions to demonstrate everything's good on our side. We *just* need the underlying packages to be released to PyPi.

I propose to keep that PR open while things get sorted out in other projects. Once proper versions will be available, I'll replace the commit target to pinned versions. Then we can merge that PR.

**Comment by kdeldycke** [comment]
Good news, [`sphinxcontrib-bibtex` 2.6.3a4 fix the issue](https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/345#issuecomment-2345760699), as you can see in the test results of this PR.

We're now waiting a `sphinxcontrib-bibtex` 2.6.3 release upstream.

**Comment by ashwinvis** [comment]
Squashed and closed via https://github.com/ashwinvis/myst-reader/commit/b93676f626cfa9e18f73be46dfca6cddd298cee6

**Pull request closed without merging**
