### PR TITLE
Bump `myst-parser` from `0.18` to `2.0`; uncap `docutils`

### PR DESCRIPTION
**Pull request by kdeldycke**
`myst-parser 0.18.0` was released a year ago, `2.0.0` has been available from a couple of days. This PR allow the use of the latest version.

For the record, the new version is wrapping citations in a `<div class="citation-list" role="list">` node, hence the update of HTML target.

The rendered HTML is still the same though:

* Old `expected`:

  expected

* New `output`:

  output

### CODE REVIEW

**Comment by kdeldycke** [comment]
@ashwinvis , can you approve the CI workflow so I can check I did not break anything? 😇

**Comment by kdeldycke** [comment]
Hey @ashwinvis , can you approve the CI workflow again? 🤗

**Comment by kdeldycke** [comment]
All tests are passing, this PR is ready to be merged upstream.

**Comment by paugier** [comment]
Thanks @kdeldycke !

**Comment by kdeldycke** [comment]
Thanks @paugier for the quick merge upstream! I'll probably a couple other PR to submit in the next few days: I'm trying to add support for MyST to my Pelican theme: https://github.com/kdeldycke/plumage

**Pull request merged**
